name: Format
on:
  workflow_dispatch:

jobs:
  codetest:
    name: Check format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install poetry
        poetry install
    - name: black
      run: |
        poetry run black --check --diff --quiet --skip-magic-trailing-comma .